graph_include = '/home/consti/Work/software/src/nifty/externals/graph/include'

kernighan_lin:
	g++ -std=c++11 -O3 -I ${graph_include} -o kernighan-lin kernighan-lin.cxx

gaec:
	g++ -std=c++11 -O3 -I ${graph_include} -o gaec gaec.cxx
